# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attrinfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='attrinfo.proto',
  package='attrinfo',
  syntax='proto3',
  serialized_options=b'Z$windplatform/server/protogo/attrinfo',
  serialized_pb=b'\n\x0e\x61ttrinfo.proto\x12\x08\x61ttrinfo\"\xb1\x01\n\x08\x41ttrInfo\x12\x10\n\x08\x61ttrType\x18\x01 \x01(\x05\x12\x14\n\nvalueInt32\x18\x02 \x01(\x05H\x00\x12\x14\n\nvalueInt64\x18\x03 \x01(\x03H\x00\x12\x16\n\x0cvalueFloat32\x18\x04 \x01(\x02H\x00\x12\x15\n\x0bvalueString\x18\x05 \x01(\tH\x00\x12\x13\n\tvalueBool\x18\x06 \x01(\x08H\x00\x12\x16\n\x0cvalueFloat64\x18\x07 \x01(\x01H\x00\x42\x0b\n\tattrValueB&Z$windplatform/server/protogo/attrinfob\x06proto3'
)




_ATTRINFO = _descriptor.Descriptor(
  name='AttrInfo',
  full_name='attrinfo.AttrInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attrType', full_name='attrinfo.AttrInfo.attrType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valueInt32', full_name='attrinfo.AttrInfo.valueInt32', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valueInt64', full_name='attrinfo.AttrInfo.valueInt64', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valueFloat32', full_name='attrinfo.AttrInfo.valueFloat32', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valueString', full_name='attrinfo.AttrInfo.valueString', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valueBool', full_name='attrinfo.AttrInfo.valueBool', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valueFloat64', full_name='attrinfo.AttrInfo.valueFloat64', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='attrValue', full_name='attrinfo.AttrInfo.attrValue',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=29,
  serialized_end=206,
)

_ATTRINFO.oneofs_by_name['attrValue'].fields.append(
  _ATTRINFO.fields_by_name['valueInt32'])
_ATTRINFO.fields_by_name['valueInt32'].containing_oneof = _ATTRINFO.oneofs_by_name['attrValue']
_ATTRINFO.oneofs_by_name['attrValue'].fields.append(
  _ATTRINFO.fields_by_name['valueInt64'])
_ATTRINFO.fields_by_name['valueInt64'].containing_oneof = _ATTRINFO.oneofs_by_name['attrValue']
_ATTRINFO.oneofs_by_name['attrValue'].fields.append(
  _ATTRINFO.fields_by_name['valueFloat32'])
_ATTRINFO.fields_by_name['valueFloat32'].containing_oneof = _ATTRINFO.oneofs_by_name['attrValue']
_ATTRINFO.oneofs_by_name['attrValue'].fields.append(
  _ATTRINFO.fields_by_name['valueString'])
_ATTRINFO.fields_by_name['valueString'].containing_oneof = _ATTRINFO.oneofs_by_name['attrValue']
_ATTRINFO.oneofs_by_name['attrValue'].fields.append(
  _ATTRINFO.fields_by_name['valueBool'])
_ATTRINFO.fields_by_name['valueBool'].containing_oneof = _ATTRINFO.oneofs_by_name['attrValue']
_ATTRINFO.oneofs_by_name['attrValue'].fields.append(
  _ATTRINFO.fields_by_name['valueFloat64'])
_ATTRINFO.fields_by_name['valueFloat64'].containing_oneof = _ATTRINFO.oneofs_by_name['attrValue']
DESCRIPTOR.message_types_by_name['AttrInfo'] = _ATTRINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AttrInfo = _reflection.GeneratedProtocolMessageType('AttrInfo', (_message.Message,), {
  'DESCRIPTOR' : _ATTRINFO,
  '__module__' : 'attrinfo_pb2'
  # @@protoc_insertion_point(class_scope:attrinfo.AttrInfo)
  })
_sym_db.RegisterMessage(AttrInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
