# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatapi.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chatapi.proto',
  package='chat.api',
  syntax='proto3',
  serialized_options=b'Z#windplatform/server/protogo/chatapi',
  serialized_pb=b'\n\rchatapi.proto\x12\x08\x63hat.api\"@\n\x0b\x43hatRequest\x12\x10\n\x08playerID\x18\x01 \x01(\t\x12\x0e\n\x06roomID\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\x1f\n\x0c\x43hatResponse\x12\x0f\n\x07retCode\x18\x01 \x01(\x05\"A\n\x0cVoiceRequest\x12\x10\n\x08playerID\x18\x01 \x01(\t\x12\x0e\n\x06roomID\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\" \n\rVoiceResponse\x12\x0f\n\x07retCode\x18\x01 \x01(\x05\x32{\n\x04\x43hat\x12\x37\n\x04\x43hat\x12\x15.chat.api.ChatRequest\x1a\x16.chat.api.ChatResponse\"\x00\x12:\n\x05Voice\x12\x16.chat.api.VoiceRequest\x1a\x17.chat.api.VoiceResponse\"\x00\x42%Z#windplatform/server/protogo/chatapib\x06proto3'
)




_CHATREQUEST = _descriptor.Descriptor(
  name='ChatRequest',
  full_name='chat.api.ChatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerID', full_name='chat.api.ChatRequest.playerID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roomID', full_name='chat.api.ChatRequest.roomID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='chat.api.ChatRequest.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=91,
)


_CHATRESPONSE = _descriptor.Descriptor(
  name='ChatResponse',
  full_name='chat.api.ChatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retCode', full_name='chat.api.ChatResponse.retCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=124,
)


_VOICEREQUEST = _descriptor.Descriptor(
  name='VoiceRequest',
  full_name='chat.api.VoiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerID', full_name='chat.api.VoiceRequest.playerID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roomID', full_name='chat.api.VoiceRequest.roomID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='chat.api.VoiceRequest.content', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=191,
)


_VOICERESPONSE = _descriptor.Descriptor(
  name='VoiceResponse',
  full_name='chat.api.VoiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retCode', full_name='chat.api.VoiceResponse.retCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=225,
)

DESCRIPTOR.message_types_by_name['ChatRequest'] = _CHATREQUEST
DESCRIPTOR.message_types_by_name['ChatResponse'] = _CHATRESPONSE
DESCRIPTOR.message_types_by_name['VoiceRequest'] = _VOICEREQUEST
DESCRIPTOR.message_types_by_name['VoiceResponse'] = _VOICERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChatRequest = _reflection.GeneratedProtocolMessageType('ChatRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHATREQUEST,
  '__module__' : 'chatapi_pb2'
  # @@protoc_insertion_point(class_scope:chat.api.ChatRequest)
  })
_sym_db.RegisterMessage(ChatRequest)

ChatResponse = _reflection.GeneratedProtocolMessageType('ChatResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHATRESPONSE,
  '__module__' : 'chatapi_pb2'
  # @@protoc_insertion_point(class_scope:chat.api.ChatResponse)
  })
_sym_db.RegisterMessage(ChatResponse)

VoiceRequest = _reflection.GeneratedProtocolMessageType('VoiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _VOICEREQUEST,
  '__module__' : 'chatapi_pb2'
  # @@protoc_insertion_point(class_scope:chat.api.VoiceRequest)
  })
_sym_db.RegisterMessage(VoiceRequest)

VoiceResponse = _reflection.GeneratedProtocolMessageType('VoiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _VOICERESPONSE,
  '__module__' : 'chatapi_pb2'
  # @@protoc_insertion_point(class_scope:chat.api.VoiceResponse)
  })
_sym_db.RegisterMessage(VoiceResponse)


DESCRIPTOR._options = None

_CHAT = _descriptor.ServiceDescriptor(
  name='Chat',
  full_name='chat.api.Chat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=227,
  serialized_end=350,
  methods=[
  _descriptor.MethodDescriptor(
    name='Chat',
    full_name='chat.api.Chat.Chat',
    index=0,
    containing_service=None,
    input_type=_CHATREQUEST,
    output_type=_CHATRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Voice',
    full_name='chat.api.Chat.Voice',
    index=1,
    containing_service=None,
    input_type=_VOICEREQUEST,
    output_type=_VOICERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAT)

DESCRIPTOR.services_by_name['Chat'] = _CHAT

# @@protoc_insertion_point(module_scope)
