# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='control.proto',
  package='control',
  syntax='proto3',
  serialized_options=b'Z#windplatform/server/protogo/control',
  serialized_pb=b'\n\rcontrol.proto\x12\x07\x63ontrol\"L\n\x16PlayerFirstControlInfo\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0e\n\x06gameId\x18\x02 \x01(\t\x12\x12\n\nmatchLevel\x18\x03 \x01(\x05\"\xa6\x02\n\x11PlayerControlInfo\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0e\n\x06gameId\x18\x02 \x01(\t\x12\x12\n\nmatchLevel\x18\x03 \x01(\x05\x12\x11\n\thandLevel\x18\x04 \x01(\t\x12\x11\n\ttakeLevel\x18\x05 \x01(\t\x12\x14\n\x0c\x63ontrolTotal\x18\x06 \x01(\x05\x12\x14\n\x0c\x63ontrolCount\x18\x07 \x01(\x05\x12\x15\n\rconditionType\x18\x08 \x01(\x05\x12\x13\n\x0b\x63onditionId\x18\t \x01(\x05\x12\x15\n\rconditionName\x18\n \x01(\t\x12\x10\n\x08\x63omboWin\x18\x0b \x01(\x05\x12\x10\n\x08totalWin\x18\x0c \x01(\x03\x12\x11\n\tcomboLose\x18\r \x01(\x05\x12\x11\n\ttotalLose\x18\x0e \x01(\x03\x42%Z#windplatform/server/protogo/controlb\x06proto3'
)




_PLAYERFIRSTCONTROLINFO = _descriptor.Descriptor(
  name='PlayerFirstControlInfo',
  full_name='control.PlayerFirstControlInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='control.PlayerFirstControlInfo.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gameId', full_name='control.PlayerFirstControlInfo.gameId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='matchLevel', full_name='control.PlayerFirstControlInfo.matchLevel', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=102,
)


_PLAYERCONTROLINFO = _descriptor.Descriptor(
  name='PlayerControlInfo',
  full_name='control.PlayerControlInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='control.PlayerControlInfo.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gameId', full_name='control.PlayerControlInfo.gameId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='matchLevel', full_name='control.PlayerControlInfo.matchLevel', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='handLevel', full_name='control.PlayerControlInfo.handLevel', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='takeLevel', full_name='control.PlayerControlInfo.takeLevel', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controlTotal', full_name='control.PlayerControlInfo.controlTotal', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controlCount', full_name='control.PlayerControlInfo.controlCount', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conditionType', full_name='control.PlayerControlInfo.conditionType', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conditionId', full_name='control.PlayerControlInfo.conditionId', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conditionName', full_name='control.PlayerControlInfo.conditionName', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comboWin', full_name='control.PlayerControlInfo.comboWin', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalWin', full_name='control.PlayerControlInfo.totalWin', index=11,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comboLose', full_name='control.PlayerControlInfo.comboLose', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalLose', full_name='control.PlayerControlInfo.totalLose', index=13,
      number=14, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=399,
)

DESCRIPTOR.message_types_by_name['PlayerFirstControlInfo'] = _PLAYERFIRSTCONTROLINFO
DESCRIPTOR.message_types_by_name['PlayerControlInfo'] = _PLAYERCONTROLINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerFirstControlInfo = _reflection.GeneratedProtocolMessageType('PlayerFirstControlInfo', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERFIRSTCONTROLINFO,
  '__module__' : 'control_pb2'
  # @@protoc_insertion_point(class_scope:control.PlayerFirstControlInfo)
  })
_sym_db.RegisterMessage(PlayerFirstControlInfo)

PlayerControlInfo = _reflection.GeneratedProtocolMessageType('PlayerControlInfo', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERCONTROLINFO,
  '__module__' : 'control_pb2'
  # @@protoc_insertion_point(class_scope:control.PlayerControlInfo)
  })
_sym_db.RegisterMessage(PlayerControlInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
