# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gameprovide.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gameprovide.proto',
  package='gameprovide',
  syntax='proto3',
  serialized_options=b'Z\'windplatform/server/protogo/gameprovide',
  serialized_pb=b'\n\x11gameprovide.proto\x12\x0bgameprovide\"Z\n\nConnectReq\x12\x0e\n\x06userId\x18\x01 \x01(\x03\x12\x0c\n\x04wsId\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\t\x12\x0e\n\x06gameId\x18\x04 \x01(\t\x12\r\n\x05token\x18\x05 \x01(\t\"\x0c\n\nConnectRsp\"]\n\rDisconnectReq\x12\x0e\n\x06userId\x18\x01 \x01(\x03\x12\x0c\n\x04wsId\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\t\x12\x0e\n\x06gameId\x18\x04 \x01(\t\x12\r\n\x05token\x18\x05 \x01(\t\"\x0f\n\rDisconnectRsp\"W\n\nMessageReq\x12\x0e\n\x06UserId\x18\x01 \x01(\x03\x12\x0c\n\x04\x44\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05Token\x18\x03 \x01(\t\x12\x0e\n\x06gameId\x18\x04 \x01(\t\x12\x0c\n\x04wsId\x18\x05 \x01(\t\"\x0c\n\nMessageRsp2\xd1\x01\n\tWebsocket\x12=\n\x07\x43onnect\x12\x17.gameprovide.ConnectReq\x1a\x17.gameprovide.ConnectRsp\"\x00\x12\x46\n\nDisconnect\x12\x1a.gameprovide.DisconnectReq\x1a\x1a.gameprovide.DisconnectRsp\"\x00\x12=\n\x07Message\x12\x17.gameprovide.MessageReq\x1a\x17.gameprovide.MessageRsp\"\x00\x42)Z\'windplatform/server/protogo/gameprovideb\x06proto3'
)




_CONNECTREQ = _descriptor.Descriptor(
  name='ConnectReq',
  full_name='gameprovide.ConnectReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='gameprovide.ConnectReq.userId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wsId', full_name='gameprovide.ConnectReq.wsId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service', full_name='gameprovide.ConnectReq.service', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gameId', full_name='gameprovide.ConnectReq.gameId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='gameprovide.ConnectReq.token', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=124,
)


_CONNECTRSP = _descriptor.Descriptor(
  name='ConnectRsp',
  full_name='gameprovide.ConnectRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=138,
)


_DISCONNECTREQ = _descriptor.Descriptor(
  name='DisconnectReq',
  full_name='gameprovide.DisconnectReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='gameprovide.DisconnectReq.userId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wsId', full_name='gameprovide.DisconnectReq.wsId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service', full_name='gameprovide.DisconnectReq.service', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gameId', full_name='gameprovide.DisconnectReq.gameId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='gameprovide.DisconnectReq.token', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=233,
)


_DISCONNECTRSP = _descriptor.Descriptor(
  name='DisconnectRsp',
  full_name='gameprovide.DisconnectRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=250,
)


_MESSAGEREQ = _descriptor.Descriptor(
  name='MessageReq',
  full_name='gameprovide.MessageReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserId', full_name='gameprovide.MessageReq.UserId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Data', full_name='gameprovide.MessageReq.Data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Token', full_name='gameprovide.MessageReq.Token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gameId', full_name='gameprovide.MessageReq.gameId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wsId', full_name='gameprovide.MessageReq.wsId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=339,
)


_MESSAGERSP = _descriptor.Descriptor(
  name='MessageRsp',
  full_name='gameprovide.MessageRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=353,
)

DESCRIPTOR.message_types_by_name['ConnectReq'] = _CONNECTREQ
DESCRIPTOR.message_types_by_name['ConnectRsp'] = _CONNECTRSP
DESCRIPTOR.message_types_by_name['DisconnectReq'] = _DISCONNECTREQ
DESCRIPTOR.message_types_by_name['DisconnectRsp'] = _DISCONNECTRSP
DESCRIPTOR.message_types_by_name['MessageReq'] = _MESSAGEREQ
DESCRIPTOR.message_types_by_name['MessageRsp'] = _MESSAGERSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectReq = _reflection.GeneratedProtocolMessageType('ConnectReq', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTREQ,
  '__module__' : 'gameprovide_pb2'
  # @@protoc_insertion_point(class_scope:gameprovide.ConnectReq)
  })
_sym_db.RegisterMessage(ConnectReq)

ConnectRsp = _reflection.GeneratedProtocolMessageType('ConnectRsp', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTRSP,
  '__module__' : 'gameprovide_pb2'
  # @@protoc_insertion_point(class_scope:gameprovide.ConnectRsp)
  })
_sym_db.RegisterMessage(ConnectRsp)

DisconnectReq = _reflection.GeneratedProtocolMessageType('DisconnectReq', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTREQ,
  '__module__' : 'gameprovide_pb2'
  # @@protoc_insertion_point(class_scope:gameprovide.DisconnectReq)
  })
_sym_db.RegisterMessage(DisconnectReq)

DisconnectRsp = _reflection.GeneratedProtocolMessageType('DisconnectRsp', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTRSP,
  '__module__' : 'gameprovide_pb2'
  # @@protoc_insertion_point(class_scope:gameprovide.DisconnectRsp)
  })
_sym_db.RegisterMessage(DisconnectRsp)

MessageReq = _reflection.GeneratedProtocolMessageType('MessageReq', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEREQ,
  '__module__' : 'gameprovide_pb2'
  # @@protoc_insertion_point(class_scope:gameprovide.MessageReq)
  })
_sym_db.RegisterMessage(MessageReq)

MessageRsp = _reflection.GeneratedProtocolMessageType('MessageRsp', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERSP,
  '__module__' : 'gameprovide_pb2'
  # @@protoc_insertion_point(class_scope:gameprovide.MessageRsp)
  })
_sym_db.RegisterMessage(MessageRsp)


DESCRIPTOR._options = None

_WEBSOCKET = _descriptor.ServiceDescriptor(
  name='Websocket',
  full_name='gameprovide.Websocket',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=356,
  serialized_end=565,
  methods=[
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='gameprovide.Websocket.Connect',
    index=0,
    containing_service=None,
    input_type=_CONNECTREQ,
    output_type=_CONNECTRSP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Disconnect',
    full_name='gameprovide.Websocket.Disconnect',
    index=1,
    containing_service=None,
    input_type=_DISCONNECTREQ,
    output_type=_DISCONNECTRSP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Message',
    full_name='gameprovide.Websocket.Message',
    index=2,
    containing_service=None,
    input_type=_MESSAGEREQ,
    output_type=_MESSAGERSP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEBSOCKET)

DESCRIPTOR.services_by_name['Websocket'] = _WEBSOCKET

# @@protoc_insertion_point(module_scope)
