# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loggersrv.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='loggersrv.proto',
  package='logger.srv',
  syntax='proto3',
  serialized_options=b'Z%windplatform/server/protogo/loggersrv',
  serialized_pb=b'\n\x0floggersrv.proto\x12\nlogger.srv\"1\n\nLogRequest\x12#\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x14.logger.srv.LogEvent\"\x1e\n\x0bLogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"s\n\x08LogEvent\x12\x10\n\x08\x64\x61taBase\x18\x01 \x01(\t\x12\x11\n\ttableName\x18\x02 \x01(\t\x12\x0f\n\x07\x61gentID\x18\x03 \x01(\t\x12\x10\n\x08playerID\x18\x04 \x01(\t\x12\x11\n\ttimeStamp\x18\x05 \x01(\t\x12\x0c\n\x04text\x18\x06 \x01(\t2B\n\x06logger\x12\x38\n\x03log\x12\x16.logger.srv.LogRequest\x1a\x17.logger.srv.LogResponse\"\x00\x42\'Z%windplatform/server/protogo/loggersrvb\x06proto3'
)




_LOGREQUEST = _descriptor.Descriptor(
  name='LogRequest',
  full_name='logger.srv.LogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='logger.srv.LogRequest.event', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=80,
)


_LOGRESPONSE = _descriptor.Descriptor(
  name='LogResponse',
  full_name='logger.srv.LogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='logger.srv.LogResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=112,
)


_LOGEVENT = _descriptor.Descriptor(
  name='LogEvent',
  full_name='logger.srv.LogEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataBase', full_name='logger.srv.LogEvent.dataBase', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tableName', full_name='logger.srv.LogEvent.tableName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agentID', full_name='logger.srv.LogEvent.agentID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerID', full_name='logger.srv.LogEvent.playerID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='logger.srv.LogEvent.timeStamp', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='logger.srv.LogEvent.text', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=229,
)

_LOGREQUEST.fields_by_name['event'].message_type = _LOGEVENT
DESCRIPTOR.message_types_by_name['LogRequest'] = _LOGREQUEST
DESCRIPTOR.message_types_by_name['LogResponse'] = _LOGRESPONSE
DESCRIPTOR.message_types_by_name['LogEvent'] = _LOGEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LogRequest = _reflection.GeneratedProtocolMessageType('LogRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGREQUEST,
  '__module__' : 'loggersrv_pb2'
  # @@protoc_insertion_point(class_scope:logger.srv.LogRequest)
  })
_sym_db.RegisterMessage(LogRequest)

LogResponse = _reflection.GeneratedProtocolMessageType('LogResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGRESPONSE,
  '__module__' : 'loggersrv_pb2'
  # @@protoc_insertion_point(class_scope:logger.srv.LogResponse)
  })
_sym_db.RegisterMessage(LogResponse)

LogEvent = _reflection.GeneratedProtocolMessageType('LogEvent', (_message.Message,), {
  'DESCRIPTOR' : _LOGEVENT,
  '__module__' : 'loggersrv_pb2'
  # @@protoc_insertion_point(class_scope:logger.srv.LogEvent)
  })
_sym_db.RegisterMessage(LogEvent)


DESCRIPTOR._options = None

_LOGGER = _descriptor.ServiceDescriptor(
  name='logger',
  full_name='logger.srv.logger',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=231,
  serialized_end=297,
  methods=[
  _descriptor.MethodDescriptor(
    name='log',
    full_name='logger.srv.logger.log',
    index=0,
    containing_service=None,
    input_type=_LOGREQUEST,
    output_type=_LOGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOGGER)

DESCRIPTOR.services_by_name['logger'] = _LOGGER

# @@protoc_insertion_point(module_scope)
