# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playerbase.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='playerbase.proto',
  package='player.base',
  syntax='proto3',
  serialized_options=b'Z&windplatform/server/protogo/playerbase',
  serialized_pb=b'\n\x10playerbase.proto\x12\x0bplayer.base\"b\n\nPlayerInfo\x12\x0e\n\x06userID\x18\x01 \x01(\t\x12\x0e\n\x06ipAddr\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x10\n\x08platform\x18\x04 \x01(\t\x12\x10\n\x08vipLevel\x18\x05 \x01(\t\"\x89\x01\n\nPlayerData\x12\x10\n\x08playerID\x18\x01 \x01(\t\x12\x0f\n\x07\x61gentID\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x10\n\x08\x61vatarID\x18\x04 \x01(\x05\x12\x10\n\x08language\x18\x05 \x01(\t\x12\x10\n\x08platform\x18\x06 \x01(\t\x12\x10\n\x08vipLevel\x18\x07 \x01(\t\"W\n\x07ResInfo\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08lobbyUrl\x18\x02 \x01(\t\x12+\n\nplayerData\x18\x03 \x01(\x0b\x32\x17.player.base.PlayerDataB(Z&windplatform/server/protogo/playerbaseb\x06proto3'
)




_PLAYERINFO = _descriptor.Descriptor(
  name='PlayerInfo',
  full_name='player.base.PlayerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userID', full_name='player.base.PlayerInfo.userID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipAddr', full_name='player.base.PlayerInfo.ipAddr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='player.base.PlayerInfo.language', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='platform', full_name='player.base.PlayerInfo.platform', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vipLevel', full_name='player.base.PlayerInfo.vipLevel', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=131,
)


_PLAYERDATA = _descriptor.Descriptor(
  name='PlayerData',
  full_name='player.base.PlayerData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerID', full_name='player.base.PlayerData.playerID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agentID', full_name='player.base.PlayerData.agentID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='player.base.PlayerData.location', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='avatarID', full_name='player.base.PlayerData.avatarID', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='player.base.PlayerData.language', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='platform', full_name='player.base.PlayerData.platform', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vipLevel', full_name='player.base.PlayerData.vipLevel', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=271,
)


_RESINFO = _descriptor.Descriptor(
  name='ResInfo',
  full_name='player.base.ResInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='player.base.ResInfo.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lobbyUrl', full_name='player.base.ResInfo.lobbyUrl', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerData', full_name='player.base.ResInfo.playerData', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=360,
)

_RESINFO.fields_by_name['playerData'].message_type = _PLAYERDATA
DESCRIPTOR.message_types_by_name['PlayerInfo'] = _PLAYERINFO
DESCRIPTOR.message_types_by_name['PlayerData'] = _PLAYERDATA
DESCRIPTOR.message_types_by_name['ResInfo'] = _RESINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerInfo = _reflection.GeneratedProtocolMessageType('PlayerInfo', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERINFO,
  '__module__' : 'playerbase_pb2'
  # @@protoc_insertion_point(class_scope:player.base.PlayerInfo)
  })
_sym_db.RegisterMessage(PlayerInfo)

PlayerData = _reflection.GeneratedProtocolMessageType('PlayerData', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERDATA,
  '__module__' : 'playerbase_pb2'
  # @@protoc_insertion_point(class_scope:player.base.PlayerData)
  })
_sym_db.RegisterMessage(PlayerData)

ResInfo = _reflection.GeneratedProtocolMessageType('ResInfo', (_message.Message,), {
  'DESCRIPTOR' : _RESINFO,
  '__module__' : 'playerbase_pb2'
  # @@protoc_insertion_point(class_scope:player.base.ResInfo)
  })
_sym_db.RegisterMessage(ResInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
